language: python
python: "3.6"
before_install:
  - export GOOGLE_MAPS_KEY=placeholder
  - export BING_MAPS_KEY=placeholder
install: pip install -r requirements.txt
script: pytest
after_success: codecov
